[package]
name = "password_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bcrypt = "0.15.0"
dialoguer = "0.11.0"
magic-crypt = "3.1.12"
serde = "1.0.188"
